Documentation Cleanup: Fix index.md link to decomposition.md
xvik/dropwizard-guicey pull request #221
Opened 2022-04-09 04:01 UTC by JKomoroski

Documentation Cleanup: decomposition.md

Been a few months since I last worked on the documentation.

2022-04-18 08:56 UTC, xvik requested changes
Thank you very much! Sorry for late reply!
Could you please correct a few points

2022-04-18 08:56 UTC, xvik commented on src/doc/docs/decomposition.md
> +additional configuration features. Even the simple use cases require some configuration of guice modules.
"Even the simple use cases require some configuration of guice modules." -> No, it's not strictly required, but may be requirwed - the simplest example is a need of gucie module registration from bundle. Maybe it should be like: "In the simplest case, you may need to apply guice modules from bundle"

2022-04-18 08:56 UTC, xvik commented on src/doc/docs/decomposition.md
> +Auto-loading is based on guicey [bundles lookup](guide/bundles.md#service-loader-lookup) algorithm.
I may not know some language nuances, but when I see an "algorithm" I imagine something sophisticated. Bundles lookup implementation is very simple (lookup and load) I don't think it deserves to be called an "algorithm". Probably a "feature" would be better.

2022-04-18 08:56 UTC, xvik commented on src/doc/docs/decomposition.md
> +requires a modified service. Your bundle may disable the core module, and install a replacement customized module:
"and install a replacement customized module" -> I think its not clear what is replacement and would be better like this: "and install a customized module as a replacement"

2022-04-27 01:42 UTC, JKomoroski commented
@xvik I've addressed your comments. Let me know if you have any other concerns.

2022-04-27 07:39 UTC, merged

2022-04-27 07:39 UTC, xvik commented
Thank you!